# Generated by Django 5.0.7 on 2024-08-28 06:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('project_id', models.CharField(max_length=2550)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('easypaisa', 'Easypaisa'), ('jazzcash', 'JazzCash')], max_length=50)),
                ('payer_name', models.CharField(max_length=255)),
                ('payer_account_number', models.CharField(max_length=20)),
                ('seller_name', models.CharField(max_length=255)),
                ('seller_account_number', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_successful', models.BooleanField(default=False)),
            ],
        ),
    ]
