# Generated by Django 5.0.7 on 2024-09-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_payment_delete_buyerpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyername', models.CharField(max_length=100)),
                ('buyeremail', models.EmailField(max_length=254)),
                ('buyermessage', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
