# Generated by Django 5.0.7 on 2024-09-13 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageApp', '0003_alter_message_receiver_alter_message_sender'),
        ('UniSeller', '0001_initial'),
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='buyer.buyersignup'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='UniSeller.sellersignupmodal'),
        ),
    ]
