# Generated by Django 5.0.7 on 2024-09-13 03:10

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GigDataModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.IntegerField()),
                ('gig_title', models.CharField(max_length=50)),
                ('field', models.CharField(max_length=50)),
                ('sub_field', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=5000)),
                ('gig_image1', models.FileField(upload_to='gig_images/')),
                ('gig_image2', models.FileField(upload_to='gig_images/')),
                ('gig_image3', models.FileField(upload_to='gig_images/')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAppliedModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('posted_by', models.CharField(default='noone', max_length=50)),
                ('seller_id', models.IntegerField()),
                ('project_price', models.IntegerField()),
                ('project_tokens', models.IntegerField()),
                ('Date_from', models.DateField()),
                ('Date_to', models.DateField()),
                ('applied_date', models.DateField(default=datetime.date.today)),
                ('cover_letter', models.CharField(max_length=5000)),
                ('status', models.CharField(default='pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SellerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellerSignUpModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('profile_picture', models.FileField(upload_to='profile_pictures/')),
                ('university_email', models.EmailField(max_length=100)),
                ('mobile_no', models.CharField(max_length=50)),
                ('university_name', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=50)),
                ('study_field', models.CharField(max_length=50)),
                ('skills', models.CharField(max_length=500)),
                ('Date', models.DateField(auto_now=True)),
                ('password', models.CharField(max_length=12)),
                ('verification_code', models.CharField(max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
