# Generated by Django 5.0.7 on 2024-08-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SellerSignUpModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('university_email', models.EmailField(max_length=100)),
                ('mobile_no', models.CharField(max_length=50)),
                ('university_name', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=50)),
                ('study_field', models.CharField(max_length=50)),
                ('skills', models.CharField(max_length=500)),
                ('Date', models.DateField(auto_now=True)),
                ('password', models.CharField(max_length=12)),
                ('verification_code', models.CharField(max_length=6)),
            ],
        ),
    ]
