# Generated by Django 5.0.7 on 2024-08-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniSeller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAppliedModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('seller_id', models.IntegerField(max_length=100)),
                ('project_price', models.IntegerField()),
                ('project_tokens', models.IntegerField()),
                ('Date_from', models.DateField()),
                ('Date_to', models.DateField()),
                ('cover_letter', models.CharField(max_length=500)),
            ],
        ),
    ]
