# Generated by Django 5.0.7 on 2024-08-12 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniSeller', '0002_projectappliedmodal'),
    ]

    operations = [
        migrations.CreateModel(
            name='GigDataModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.IntegerField()),
                ('gig_title', models.CharField(max_length=50)),
                ('field', models.CharField(max_length=50)),
                ('sub_field', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('gig_price', models.IntegerField()),
                ('gig_image1', models.ImageField(upload_to='gig_images/')),
                ('gig_image2', models.ImageField(upload_to='gig_images/')),
                ('gig_image3', models.ImageField(upload_to='gig_images/')),
            ],
        ),
    ]
