# Generated by Django 5.0.7 on 2024-08-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniSeller', '0002_remove_gigdatamodal_gig_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectappliedmodal',
            name='seller_id',
            field=models.IntegerField(),
        ),
    ]
