# Generated by Django 5.0.7 on 2024-08-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniSeller', '0003_gigdatamodal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gigdatamodal',
            name='gig_image1',
            field=models.FileField(upload_to='gig_images/'),
        ),
        migrations.AlterField(
            model_name='gigdatamodal',
            name='gig_image2',
            field=models.FileField(upload_to='gig_images/'),
        ),
        migrations.AlterField(
            model_name='gigdatamodal',
            name='gig_image3',
            field=models.FileField(upload_to='gig_images/'),
        ),
    ]
