# Generated by Django 5.0.7 on 2024-08-13 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniSeller', '0003_alter_projectappliedmodal_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectappliedmodal',
            name='seller_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniSeller.sellersignupmodal'),
        ),
    ]
