# Generated by Django 5.0.7 on 2024-08-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniSeller', '0004_alter_projectappliedmodal_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectappliedmodal',
            name='seller_id',
            field=models.IntegerField(),
        ),
    ]
