# Generated by Django 5.0.7 on 2024-08-14 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniSeller', '0005_alter_projectappliedmodal_seller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectappliedmodal',
            name='applied_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='projectappliedmodal',
            name='posted_by',
            field=models.CharField(default='noone', max_length=50),
        ),
    ]
