# Generated by Django 5.0.7 on 2024-08-15 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniSeller', '0006_projectappliedmodal_applied_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectappliedmodal',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='gigdatamodal',
            name='description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='projectappliedmodal',
            name='cover_letter',
            field=models.CharField(max_length=5000),
        ),
    ]
