# Generated by Django 5.0.7 on 2024-09-04 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniSeller', '0007_projectappliedmodal_status_and_more'),
        ('buyer', '0004_payment_delete_buyerpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_rooms', to='buyer.buyersignup')),
                ('uniseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_rooms', to='UniSeller.sellersignupmodal')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_is_seller', models.BooleanField()),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='UniSeller.chatroom')),
            ],
        ),
    ]
