# Generated by Django 5.0.7 on 2024-09-04 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniSeller', '0008_chatroom_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
